import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check, CloudCog, Cpu, DatabaseBackup, GraduationCap, Headphones, Laptop, Network, PackageCheck, Printer, ScanEye, ServerCog, ShieldCheck, Video } from 'lucide-react'
import { StandardPage, SectionHead } from '@/components/Blocks'

const catalogue = [
  { icon: ServerCog, group:'Infrastructure', title:'Enterprise IT Infrastructure', text:'Servers, storage, virtualization and resilient core systems designed around your business.', image:'/images/server-room.jpg', points:['Assessment & architecture','Deployment & modernization'] },
  { icon: CloudCog, group:'Cloud', title:'Microsoft Azure & Hybrid Cloud', text:'Cloud strategy, Microsoft 365 and secure connections between Azure and on-premises systems.', image:'/images/cloud-maintenance-new.jpg', points:['Azure migration','Microsoft 365 services'] },
  { icon: ShieldCheck, group:'Security', title:'Cybersecurity', text:'Layered endpoint, identity, email and network protection with practical risk management.', image:'/images/security.jpg', points:['Security assessment','Protection & hardening'] },
  { icon: DatabaseBackup, group:'Resiliency', title:'Backup & Disaster Recovery', text:'Protected, tested backups and recovery plans that keep critical information available.', image:'/images/backup-recovery.jpg', points:['Local & cloud backup','Recovery testing'] },
  { icon: Network, group:'Connectivity', title:'Networking & Wi-Fi', text:'Reliable wired, wireless, VPN and branch connectivity with visibility and security built in.', image:'/images/networking-wifi-new.jpg', points:['LAN, WAN & Wi-Fi','Firewall & VPN'] },
  { icon: Headphones, group:'Managed IT', title:'Monitoring & Managed Services', text:'Proactive maintenance, help desk and on-site assistance under one accountable service team.', image:'/images/security.jpg', points:['Monitoring & patching','Remote & field support'] },
  { icon: Laptop, group:'Device Support', title:'Laptop & Desktop Support', text:'Diagnosis, upgrades, OS support and reliable repairs for business and personal computers.', image:'/images/laptop-desktop-repair-new.jpg', points:['Hardware diagnosis','Upgrade & repair'] },
  { icon: Printer, group:'Office Support', title:'Printer & Peripheral Support', text:'Setup, troubleshooting and maintenance for printers, scanners and essential office equipment.', image:'/images/printer-maintenance-new.jpg', points:['Printer installation','Repair & maintenance'] },
  { icon: Video, group:'Physical Security', title:'CCTV & Surveillance', text:'IP camera systems planned for useful coverage, recording retention and secure remote access.', image:'/images/cctv-service-new.jpg', points:['Camera & NVR setup','Remote monitoring'] },
  { icon: PackageCheck, group:'Procurement', title:'IT Products & Licensing', text:'Genuine business hardware, software and subscriptions sourced with expert technical guidance.', image:'/images/device-support.jpg', points:['Hardware procurement','Software licensing'] },
  { icon: Cpu, group:'Performance Systems', title:'Custom PCs & Workstations', text:'Purpose-built systems balanced for engineering, creative, business and performance workloads.', image:'/images/device-support.jpg', points:['Component planning','Assembly & testing'] },
  { icon: GraduationCap, group:'Training', title:'Practical Technical Training', text:'Hands-on learning for students, professionals and teams across hardware, cloud and networking.', image:'/images/training.jpg', points:['Lab-led learning','Corporate upskilling'] },
  { icon: ScanEye, group:'Advisory', title:'IT Health Checks & Consulting', text:'A clear current-state review, prioritized risks and a practical roadmap for improvement.', image:'/images/security.jpg', points:['Infrastructure review','Actionable roadmap'] },
]

export default function ServicesPage(){return <StandardPage seo="Complete IT Services" eyebrow="Services" title="One team for your complete technology environment." text="From enterprise cloud and cybersecurity to laptop, printer and CCTV support, DgITmatrix brings every technology need under one accountable local partner." image="/images/device-support.jpg">
  <section className="section services-catalogue"><div className="shell"><SectionHead kicker="Complete service catalogue" title="Everything your organization needs to stay connected, protected and productive." text="Choose a focused project or bring your complete IT environment under one managed relationship."/>
  <div className="service-catalogue-grid">{catalogue.map(({icon:Icon,group,title,text,image,points},index)=><article className={`catalogue-card tone-${index%3}`} key={title}><div className="catalogue-visual"><Image src={image} alt="" fill sizes="(max-width: 700px) 100vw, (max-width: 1100px) 50vw, 33vw"/><span><Icon/> {group}</span></div><div className="catalogue-copy"><h2>{title}</h2><p>{text}</p><ul>{points.map(point=><li key={point}><Check/>{point}</li>)}</ul><Link href="/contact">Discuss this service <ArrowRight/></Link></div></article>)}</div></div></section>
  <section className="section section-dark"><div className="shell"><SectionHead light kicker="One accountable partner" title="Enterprise capability. Local response." text="Our services connect strategically: infrastructure supports cloud, security protects access, backup safeguards data, and managed support keeps it all running."/><div className="process">{[['01','Assess','Understand the current environment and business priorities.'],['02','Plan','Define scope, outcomes, costs and a safe delivery path.'],['03','Implement','Deploy, test and document with minimal interruption.'],['04','Support','Monitor, maintain and improve through one local team.']].map(x=><div key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
  </StandardPage>}
