import Link from 'next/link'
import { ArrowRight, Check, CloudCog, Cpu, GraduationCap, Network, ShieldCheck, Wrench } from 'lucide-react'
import { StandardPage, SectionHead } from '@/components/Blocks'

const courses=[
 {icon:Cpu,level:'Foundation',title:'Computer Hardware & PC Assembly',text:'Understand components, assemble systems, install operating systems and diagnose common hardware faults.',skills:['Components & compatibility','Assembly and OS setup','Preventive maintenance']},
 {icon:Network,level:'Core Track',title:'Networking Fundamentals',text:'Build practical confidence with IP addressing, switching, routing, Wi-Fi and structured networks.',skills:['TCP/IP and subnetting','LAN and wireless setup','Network troubleshooting']},
 {icon:CloudCog,level:'Cloud Track',title:'Microsoft Cloud Foundations',text:'Learn the practical building blocks behind Microsoft 365, identity and Azure cloud services.',skills:['Microsoft 365 basics','Azure fundamentals','Users and permissions']},
 {icon:ShieldCheck,level:'Security Track',title:'Cybersecurity Fundamentals',text:'Develop safe technical habits and understand endpoint, identity, network and data protection.',skills:['Threat awareness','Endpoint protection','Backup and recovery']},
 {icon:Wrench,level:'Service Track',title:'IT Support & Troubleshooting',text:'Work through real support scenarios and learn a repeatable method for diagnosis and resolution.',skills:['Ticket handling','Desktop support','Customer communication']},
 {icon:GraduationCap,level:'Team Track',title:'Corporate & Custom Training',text:'Focused modules for business teams, institutions and working professionals with flexible delivery.',skills:['Custom curriculum','Hands-on workshops','Team upskilling']},
]

export default function TrainingPage(){return <StandardPage seo="Practical IT Training in Kadapa" eyebrow="DgITmatrix Training" title="Learn the work, not just the theory." text="Practical, instructor-led technical training in Kadapa for students, professionals and business teams—built around real systems, guided labs and workplace scenarios." image="/images/training.jpg">
 <section className="section training-intro"><div className="shell training-promise"><div><SectionHead kicker="A lab-first approach" title="Build confidence with your hands on the technology." text="Each track moves from clear fundamentals to guided configuration and troubleshooting. Learners practice the reasoning expected in real support and infrastructure roles."/></div><div className="training-stats"><div><b>70%</b><span>Practical lab focus</span></div><div><b>Small</b><span>Learning batches</span></div><div><b>Local</b><span>Kadapa instruction</span></div><div><b>Real</b><span>Workplace scenarios</span></div></div></div></section>
 <section className="section section-gray"><div className="shell"><SectionHead kicker="Training tracks" title="Choose a technical direction and start building useful skills."/><div className="course-grid">{courses.map(({icon:Icon,level,title,text,skills})=><article className="course-card" key={title}><div className="course-icon"><Icon/></div><small>{level}</small><h2>{title}</h2><p>{text}</p><ul>{skills.map(x=><li key={x}><Check/>{x}</li>)}</ul><Link href="/contact">Ask about this course <ArrowRight/></Link></article>)}</div></div></section>
 <section className="section"><div className="shell"><SectionHead kicker="Learning journey" title="From first principle to practical task."/><div className="process">{[['01','Understand','Learn the concept and why it matters in a working environment.'],['02','Configure','Follow guided labs using systems, devices and realistic scenarios.'],['03','Troubleshoot','Find faults methodically, document findings and verify the fix.'],['04','Prepare','Connect technical ability to interviews, support work and next-level study.']].map(x=><div key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
 </StandardPage>}
